name: Dependabot
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Setup Java version'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
